name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of deployable artifacts files
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: the output of the step
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -R
      - name: Output information
        run: echo "Deploying & uploading.."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
